
-- Create Tables
CREATE TABLE IF NOT EXISTS app.menus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    icon TEXT,
    url TEXT,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app.features (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    module TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Data for app.menus
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:menus:cadastro:pessoas', 'Pessoas', 'Person', '/peoples', 'Cadastros') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:menus:cadastro:categorias', 'Categ. Produtos', 'Category', '/produtos/categorias', 'Cadastros') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:pessoas:tipos-relacionamento:listar', 'Tipos Relacionamento', 'Share', '/relationship-types', 'Cadastros') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:menus:cadastro:produtos', 'Produtos', 'LocalOffer', '/produtos', 'Cadastros') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:produtos:lista-produtos:vitrine', 'Lista de Produtos', 'ListAlt', '/lista-produtos', 'Cadastros') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:pluvyt-clients:listar', 'Clientes', 'AssignmentInd', '/peoples?view=clientes-pluvyt', 'PLUVYT') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:recompensas:listar', 'Itens de Recompensa', 'Redeem', '/produtos?view=itens-de-recompensa', 'PLUVYT') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:tenants:pluvyt:listar', 'Estabelecimentos', 'Store', '/pluvyt/estabelecimentos', 'PLUVYT') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:transacoes-pontos:listar', 'Transações', 'CurrencyExchange', '/pluvyt/transacoes', 'PLUVYT') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:restaurante:dashboard:visualizar', 'Indicadores', 'Dashboard', '/restaurante/indicadores', 'Restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:cardapio:itens:listar', 'Cardápio', 'Fastfood', '/cardapio', 'Restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:mesas:listar', 'Mesas', 'TableRestaurant', '/restaurante/mesas', 'Restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:comandas:listar', 'Comandas / Vendas', 'ReceiptLong', '/restaurante/comandas', 'Restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:restaurante:historico:listar', 'Histórico de Pedidos', 'History', '/restaurante/historico', 'Restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:kds:operacional', 'Operacional (KDS)', 'Timer', '/restaurante/kds', 'Restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:identidade-visual:listar', 'Identidade Visual', 'Brush', '/personalizacao/identidade-visual', 'Site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:landing-pages:listar', 'Landing Page', 'DashboardCustomize', '/personalizacao/landing-page', 'Site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:pessoas:vitrine', 'Lojas', 'Store', '/peoples?view=ecommercelojas', 'Vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:produtos:vitrine', 'Produtos', 'Category', '/produtos?view=ecommerce-produtos', 'Vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:produtos:lista-produtos:vitrine', 'Vitrine', 'Storefront', '/lista-produtos?view=vitrine-vitrine', 'Vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:remetentes-smtp:listar', 'Remetentes', 'ForwardToInbox', '/comunicacoes/remetentes', 'Comunicações') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;
INSERT INTO app.menus (key, name, icon, url, category) VALUES ('erp:campanhas-disparo:listar', 'Disparos', 'Campaign', '/comunicacoes/comunicacoes', 'Comunicações') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, url = EXCLUDED.url, category = EXCLUDED.category;

-- Data for app.features
INSERT INTO app.features (key, name, description, module) VALUES ('erp:dashboard', '[Dashboard] Acessar', '[Dashboard] Permite visualizar o painel principal', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:usuarios:listar', '[Usuários] Listar', '[Usuários] Permite visualizar a listagem completa de usuários', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:usuarios:visualizar', '[Usuários] Visualizar Detalhes', '[Usuários] Permite visualizar os detalhes de um usuário específico', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:usuarios:criar', '[Usuários] Criar', '[Usuários] Permite cadastrar novos usuários no sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:usuarios:editar', '[Usuários] Editar', '[Usuários] Permite alterar dados de usuários existentes', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:usuarios:excluir', '[Usuários] Excluir', '[Usuários] Permite remover usuários do sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:usuarios:atribuir-grupos', '[Usuários] Gerenciar Grupos', '[Usuários] Permite atribuir ou remover grupos de acesso de um usuário', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:usuarios:resetar-senha', '[Usuários] Resetar Senha', '[Usuários] Permite enviar email de redefinição de senha para o usuário', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:grupos-acesso:listar', '[Grupos de Acesso] Listar', '[Grupos de Acesso] Permite visualizar a listagem de grupos de permissões', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:grupos-acesso:visualizar', '[Grupos de Acesso] Visualizar Detalhes', '[Grupos de Acesso] Permite visualizar as funcionalidades vinculadas a um grupo', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:grupos-acesso:criar', '[Grupos de Acesso] Criar', '[Grupos de Acesso] Permite criar novos perfis de permissão', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:grupos-acesso:editar', '[Grupos de Acesso] Editar', '[Grupos de Acesso] Permite alterar dados e permissões de um grupo', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:grupos-acesso:excluir', '[Grupos de Acesso] Excluir', '[Grupos de Acesso] Permite remover grupos de acesso', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:autenticacao:listar-funcionalidades', '[Sistema] Listar Funcionalidades', '[Sistema] Permite listar todas as funcionalidades disponíveis no sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:autenticacao:check-permission', '[Sistema] Verificar Permissão', '[Sistema] Permite verificar se o usuário tem permissão para acessar uma URL', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:menus:listar', '[Sistema] Listar Menus', '[Sistema] Permite visualizar a estrutura de menus do sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:listar', '[Pessoas] Listar', '[Pessoas] Visualize a listagem de pessoas cadastradas', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:visualizar', '[Pessoas] Visualizar Detalhes', '[Pessoas] Visualize ficha completa de uma pessoa', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:criar', '[Pessoas] Criar', '[Pessoas] Cadastrar novas pessoas', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:editar', '[Pessoas] Editar', '[Pessoas] Alterar dados cadastrais de pessoas', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:excluir', '[Pessoas] Excluir', '[Pessoas] Remover pessoas do sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:tipos-relacionamento:listar', '[Pessoas] Listar Tipos de Relacionamento', '[Pessoas] Permite visualizar a listagem de tipos de relacionamento', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:tipos-relacionamento:visualizar', '[Pessoas] Visualizar Tipo de Relacionamento', '[Pessoas] Permite visualizar os detalhes de um tipo de relacionamento', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:tipos-relacionamento:criar', '[Pessoas] Criar Tipo de Relacionamento', '[Pessoas] Permite criar novos tipos de relacionamento', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:tipos-relacionamento:editar', '[Pessoas] Editar Tipo de Relacionamento', '[Pessoas] Permite alterar tipos de relacionamento existentes', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:tipos-relacionamento:excluir', '[Pessoas] Excluir Tipo de Relacionamento', '[Pessoas] Permite remover tipos de relacionamento do sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:tenants:listar', '[Tenants] Listar', '[Tenants] Visualize a listagem de tenants cadastrados', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:tenants:visualizar', '[Tenants] Visualizar Detalhes', '[Tenants] Visualize ficha completa de um tenant', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:tenants:criar', '[Tenants] Criar', '[Tenants] Cadastrar novos tenants', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:tenants:editar', '[Tenants] Editar', '[Tenants] Alterar dados cadastrais de tenants', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:tenants:excluir', '[Tenants] Excluir', '[Tenants] Remover tenants do sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:tenants:pluvyt:listar', '[Pluvyt] Listar Estabelecimentos', '[Pluvyt] Visualize a listagem de estabelecimentos vinculados ao programa Pluvyt', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pluvyt-clients:listar', '[Pluvyt] Listar Clientes', '[Pluvyt] Visualize a listagem de clientes do programa Pluvyt', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pluvyt-clients:visualizar', '[Pluvyt] Visualizar Detalhes do Cliente', '[Pluvyt] Veja o saldo e histórico do cliente', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pluvyt-clients:criar', '[Pluvyt] Categorizar Cliente', '[Pluvyt] Transforme uma pessoa em cliente Pluvyt', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pluvyt-clients:editar', '[Pluvyt] Editar Cliente', '[Pluvyt] Altere saldo e dados do cliente', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pluvyt-clients:excluir', '[Pluvyt] Excluir Cliente', '[Pluvyt] Remover vínculo Pluvyt da pessoa', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pluvyt:creditar-pontos', '[Pluvyt] Creditar Pontos', '[Pluvyt] Permite realizar o crédito manual de pontos para clientes Pluvyt através do Valor da Compra', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:listar', '[Produtos] Listar', '[Produtos] Visualize a listagem de produtos cadastrados', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:visualizar', '[Produtos] Visualizar Detalhes', '[Produtos] Visualize ficha completa e dashboard de um produto', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:criar', '[Produtos] Criar', '[Produtos] Cadastrar novos produtos', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:editar', '[Produtos] Editar', '[Produtos] Alterar dados cadastrais e complementares de produtos', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:excluir', '[Produtos] Excluir', '[Produtos] Remover produtos do sistema', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:recompensas:listar', '[Pluvyt] Listar Recompensas', '[Pluvyt] Visualize a listagem de itens de recompensa', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:recompensas:visualizar', '[Pluvyt] Visualizar Detalhes da Recompensa', '[Pluvyt] Visualize detalhes de um item de recompensa', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:recompensas:criar', '[Pluvyt] Criar Recompensa', '[Pluvyt] Cadastrar novos itens de recompensa', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:recompensas:editar', '[Pluvyt] Editar Recompensa', '[Pluvyt] Alterar dados das recompensas', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:recompensas:excluir', '[Pluvyt] Excluir Recompensa', '[Pluvyt] Remover itens de recompensa do sistema', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:transacoes-pontos:listar', '[Pluvyt] Listar Transações', '[Pluvyt] Visualize o histórico de transações de pontos', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:transacoes-pontos:visualizar', '[Pluvyt] Visualizar Detalhes da Transação', '[Pluvyt] Visualize detalhes de uma movimentação de pontos', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:transacoes-pontos:criar', '[Pluvyt] Criar Lançamento de Pontos', '[Pluvyt] Realizar lançamentos manuais de débito ou crédito', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:transacoes-pontos:editar', '[Pluvyt] Editar Transação', '[Pluvyt] Alterar dados de uma transação existente', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:transacoes-pontos:excluir', '[Pluvyt] Excluir Transação', '[Pluvyt] Remover registro de transação do sistema', 'pluvyt') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:cardapio:itens:listar', '[Restaurante] Listar Cardápio', '[Restaurante] Ver itens do cardápio', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:cardapio:itens:visualizar', '[Restaurante] Visualizar Item Cardápio', '[Restaurante] Detalhes do item do cardápio', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:cardapio:itens:criar', '[Restaurante] Criar Item Cardápio', '[Restaurante] Criar itens do cardápio', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:cardapio:itens:editar', '[Restaurante] Editar Item Cardápio', '[Restaurante] Editar itens do cardápio', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:cardapio:itens:excluir', '[Restaurante] Excluir Item Cardápio', '[Restaurante] Excluir itens do cardápio', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:categorias:listar', '[Produtos] Listar Categorias', '[Produtos] Visualize as categorias globais e locais de produtos', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:categorias:visualizar', '[Produtos] Visualizar Detalhes Categoria', '[Produtos] Ver ficha completa da categoria', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:categorias:criar', '[Produtos] Criar Categoria', '[Produtos] Cadastrar novas categorias de produtos', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:categorias:editar', '[Produtos] Editar Categoria', '[Produtos] Alterar dados das categorias', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:categorias:excluir', '[Produtos] Excluir Categoria', '[Produtos] Remover categorias locais', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:mesas:listar', '[Restaurante] Listar Mesas', '[Restaurante] Visualize a listagem de mesas', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:mesas:visualizar', '[Restaurante] Visualizar Detalhes Mesa', '[Restaurante] Ver ficha completa da mesa', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:mesas:criar', '[Restaurante] Criar Mesa', '[Restaurante] Cadastrar novas mesas', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:mesas:editar', '[Restaurante] Editar Mesa', '[Restaurante] Alterar dados das mesas', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:mesas:excluir', '[Restaurante] Excluir Mesa', '[Restaurante] Remover mesas', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:comandas:listar', '[Restaurante] Listar Comandas', '[Restaurante] Visualize a listagem de comandas abertas e fechadas', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:comandas:visualizar', '[Restaurante] Visualizar Detalhes Comanda', '[Restaurante] Ver ficha completa e itens da comanda', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:comandas:criar', '[Restaurante] Abrir Comanda', '[Restaurante] Abrir nova comanda para uma mesa', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:comandas:editar', '[Restaurante] Gerenciar Comanda', '[Restaurante] Acrescentar itens ou alterar dados da comanda', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:comandas:excluir', '[Restaurante] Cancelar Comanda', '[Restaurante] Remover ou cancelar uma comanda', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:notificacoes:receber-alertas', '[Notificações] Receber Alertas', '[Notificações] Permite que o usuário receba notificações via WebSocket de novos pedidos e eventos', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:notificacoes:listar', '[Notificações] Listar', '[Notificações] Permite visualizar a central de notificações', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:notificacoes:marcar-lida', '[Notificações] Marcar como Lida', '[Notificações] Permite marcar uma notificação individual como lida', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:notificacoes:marcar-nao-lida', '[Notificações] Marcar como Não Lida', '[Notificações] Permite marcar uma notificação individual como não lida', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:notificacoes:marcar-todas-lidas', '[Notificações] Marcar Todas como Lidas', '[Notificações] Permite marcar todas as notificações do tenant como lidas de uma vez', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:identidade-visual:listar', '[Site] Gerenciar Identidade Visual', '[Site] Permite configurar o logotipo, tipografia e cores da plataforma', 'site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:landing-pages:listar', '[Site] Listar Landing Pages', '[Site] Visualizar a lista de Landing Pages', 'site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:landing-pages:visualizar', '[Site] Visualizar Landing Page', '[Site] Ver detalhes de uma Landing Page específica', 'site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:landing-pages:criar', '[Site] Criar Landing Page', '[Site] Criar novas Landing Pages', 'site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:landing-pages:editar', '[Site] Editar Landing Page', '[Site] Editar informações e conteúdo de Landing Pages', 'site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:landing-pages:excluir', '[Site] Excluir Landing Page', '[Site] Remover Landing Pages do sistema', 'site') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:pessoas:vitrine', '[Loja Virtual] Acessar Lojas', 'Permite visualizar as lojas da vitrine', 'vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:vitrine', '[Loja Virtual] Acessar Produtos', 'Permite visualizar o catálogo de produtos da vitrine', 'vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:lista-produtos:vitrine', '[Loja Virtual] Listar Listas de Produtos', 'Permite visualizar as listas de produtos da vitrine', 'vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:lista:visualizar', '[Loja Virtual] Visualizar Lista de Produto', '[Loja Virtual] Visualizar os detalhes e produtos de uma lista específica', 'vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:lista:criar', '[Loja Virtual] Criar Lista de Produto', '[Loja Virtual] Criar novas listas de produtos', 'vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:lista:editar', '[Loja Virtual] Alterar dados de listas de produtos', 'vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:produtos:lista:excluir', '[Loja Virtual] Remover listas de produtos do sistema', 'vitrine') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:restaurante:historico:listar', '[Restaurante] Listar Histórico Pedidos', '[Restaurante] Permite visualizar o histórico completo de pedidos realizados', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:restaurante:historico:visualizar', '[Restaurante] Visualizar Detalhes Pedido', '[Restaurante] Permite visualizar os itens e status de um pedido específico', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:operacional', '[Restaurante] KDS Operacional', '[Restaurante] Acesso ao painel de Cozinha (Kitchen Display System) para gestão de pedidos', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:restaurante:dashboard:visualizar', '[Restaurante] Visualizar Dashboard Pedidos', '[Restaurante] Permite visualizar o painel de indicadores e gráficos de pedidos', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:restaurante:metas:editar', '[Restaurante] Editar Metas', '[Restaurante] Permite configurar os tempos ideais de atendimento e preparo', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:todos:ler', '[Restaurante] KDS Visualizar Todas Abas', '[Restaurante] Permite visualizar todas as abas e cards do KDS independente do status', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:todos:editar', '[Restaurante] KDS Gerenciar Todos Status', '[Restaurante] Permite alterar o status de qualquer card no KDS', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:novo:ler', '[Restaurante] KDS Ler Pedidos Novos', '[Restaurante] Permite visualizar pedidos com status NOVO no KDS', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:novo:editar', '[Restaurante] KDS Gerenciar Pedidos Novos', '[Restaurante] Permite alterar o status de pedidos NOVOS para EM_PREPARO', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:em_preparo:ler', '[Restaurante] KDS Ler Pedidos Em Preparo', '[Restaurante] Permite visualizar pedidos EM_PREPARO no KDS', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:em_preparo:editar', '[Restaurante] KDS Gerenciar Pedidos Em Preparo', '[Restaurante] Permite finalizar o preparo de pedidos', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:pronto:ler', '[Restaurante] KDS Ler Pedidos Prontos', '[Restaurante] Permite visualizar pedidos PRONTOS para entrega', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:pronto:editar', '[Restaurante] KDS Gerenciar Pedidos Prontos', '[Restaurante] Permite marcar pedidos PRONTOS como entregues', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:atrasado:ler', '[Restaurante] KDS Ler Pedidos Atrasados', '[Restaurante] Permite visualizar a aba de pedidos atrasados', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:cancelado:ler', '[Restaurante] KDS Ler Pedidos Cancelados', '[Restaurante] Permite visualizar pedidos cancelados na gestão do KDS', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:entregue:ler', '[Restaurante] KDS Ler Pedidos Entregues', '[Restaurante] Permite visualizar pedidos entregues/finalizados no KDS', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:kds:status:entregue:editar', '[Restaurante] KDS Gerenciar Pedidos Entregues', '[Restaurante] Permite restaurar ou gerenciar pedidos que já foram entregues', 'restaurante') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:remetentes-smtp:listar', '[Comunicações] Listar Remetentes SMTP', '[Comunicações] Permite visualizar a listagem de remetentes de e-mail', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:remetentes-smtp:visualizar', '[Comunicações] Visualizar Detalhes Remetente', '[Comunicações] Permite visualizar os detalhes de um remetente SMTP', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:remetentes-smtp:criar', '[Comunicações] Criar Remetente', '[Comunicações] Permite cadastrar novos remetentes SMTP', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:remetentes-smtp:editar', '[Comunicações] Editar Remetente', '[Comunicações] Permite alterar dados de remetentes existentes', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:remetentes-smtp:excluir', '[Comunicações] Excluir Remetente', '[Comunicações] Permite remover remetentes SMTP', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:campanhas-disparo:listar', '[Comunicações] Listar Campanhas de Disparo', '[Comunicações] Permite visualizar a listagem de campanhas de e-mail', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:campanhas-disparo:visualizar', '[Comunicações] Visualizar Detalhes Campanha', '[Comunicações] Permite visualizar os detalhes de uma campanha', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:campanhas-disparo:criar', '[Comunicações] Criar Campanha', '[Comunicações] Permite criar novas campanhas de disparo', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:campanhas-disparo:editar', '[Comunicações] Editar Campanha', '[Comunicações] Permite alterar campanhas existentes', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:campanhas-disparo:excluir', '[Comunicações] Excluir Campanha', '[Comunicações] Permite remover campanhas do sistema', 'comunicacoes') ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:config:grupos-acesso:visualizar', '[Config] Grupos de Acesso - Visualizar Menu', '[Config] Permite visualizar o card de Grupos de Acesso nas configurações', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:config:identidade-visual:visualizar', '[Config] Identidade Visual - Visualizar Menu', '[Config] Permite visualizar o card de Identidade Visual nas configurações', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:config:tenants:visualizar', '[Config] Tenants - Visualizar Menu', '[Config] Permite visualizar o card de Tenants nas configurações', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:menus:cadastro:pessoas', '[Menu] Cadastro - Pessoas', 'Permite visualizar o menu de Pessoas no grupo de Cadastros', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:menus:cadastro:produtos', '[Menu] Cadastro - Produtos', 'Permite visualizar o menu de Produtos no grupo de Cadastros', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:menus:cadastro', '[Menu] Cadastros', '[Menu] Permite visualizar a seção de Cadastros no menu lateral', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;
INSERT INTO app.features (key, name, description, module) VALUES ('erp:menus:cadastro:categorias', '[Menu] Cadastros - Categ. Produtos', '[Menu] Permite visualizar o menu de Categorias de Produtos em Cadastros', NULL) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, module = EXCLUDED.module;

