name: Build and Deploy - API Concordia Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_main:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: main
      port_mapping: "3337"
      image_tag_fallback: latest
    secrets: inherit
