name: Build and Deploy - API Concordia Homolog

on:
  push:
    branches: [ "homolog" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_homolog:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: homolog
      port_mapping: "5337"
      image_tag_fallback: homolog
    secrets: inherit
